---
- name: Install Java
  apt:
    name: default-jdk
    state: latest

- name: Copy systemd service file for the application
  template:
    src: myapp.service.j2
    dest: /etc/systemd/system/myapp.service

- name: Enable and start myapp service
  systemd:
    name: myapp
    enabled: yes
    state: started
